In [7]:
import pandas as pd
df_m = pd.read_excel('csv/bilan_debats.xlsx')
df_m.set_index('Jour', inplace=True)
df_m.to_json('csv/bilan_debats.json', orient='split')

In [8]:
df_m

,Jean-Luc Bennahmias,Benoît Hamon,Arnaud Montebourg,Vincent Peillon,Sylvia Pinel,François de Rugy,Manuel Valls
Jour,,,,,,,
8 janvier,0,9,7,9,1,0,6
9 janvier,1,6,5,3,2,0,5
10 janvier,0,6,5,2,1,0,3
11 janvier,1,5,4,2,1,0,4
12 janvier,25,13,14,9,33,9,10
13 janvier,12,10,11,4,9,3,7
14 janvier,3,6,5,2,2,1,7
15 janvier,13,15,15,7,16,6,12
16 janvier,7,10,10,2,5,2,6
17 janvier,5,6,5,2,3,1,67
18 janvier,2,7,5,3,2,1,100
19 janvier,12,18,15,7,18,8,39
20 janvier,4,12,9,2,4,5,18